from setuptools import setup, find_packages

setup(
    name="lavigen",
    version="0.1.0",
    description="Repurposing 3D Generative Model for Autoregressive Layout Generation",
    author="Haoran Feng, Yifan Niu, Zehuan Huang, Yang-Tian Sun, Chunchao Guo, Yuxin Peng, Lu Sheng",
    url="https://github.com/fenghora/LaviGen",
    packages=find_packages(),
    python_requires=">=3.10",
    install_requires=[
        # "bitsandbytes",
        # "decord",
        # "diffusers>=0.36.0",
        # "einops",
        # "imageio",
        # "jaxtyping",
        # "matplotlib",
        # "numpy",
        # "omegaconf>=2.3.0",
        # "open3d",
        # "packaging",
        # "Pillow",
        # "psutil",
        # "pytorch_lightning>=2.0.0",
        # "requests",
        # "safetensors",
        # "scipy",
        # "torch>=2.0.0",
        # "torchvision",
        # "tqdm",
        # "transformers>=4.40.0",
        # "trimesh",
        # "typeguard",
        # "utils3d",
    ],
)
